#!/bin/sh

### BEGIN INIT INFO
# Provides:        ts-M1M3thermal
# Required-Start:  $network $remote_fs
# Required-Stop:   $network $remote_fs
# Default-Start:   2 3 4 5
# Default-Stop:    6
# Short-Description: Start TS VMS (Vibration Monitor System) daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/bin:/usr/sbin

DAEMON=/usr/sbin/ts-M1M3thermald
PIDFILE=/var/run/ts-M1M3thermald.pid

# rcS contains TICKADJ
test -r /etc/default/rcS && . /etc/default/rcS

# Source function library.
. /etc/init.d/functions

# Source devices, export all variables
set -a
. /etc/default/ts-M1M3thermal
set +a

startdaemon(){
	echo -n "Starting TS M1M3 thermal:"
	start-stop-daemon --start --oknodo --pidfile ${PIDFILE} --startas $DAEMON -- -p ${PIDFILE} -u m1m3:m1m3
	echo "done"
}

stopdaemon(){
	echo -n "Stopping TS M1M3 thermal:"
	start-stop-daemon --stop --remove-pidfile --retry 5 -p ${PIDFILE}
        if [ $? == 0 ]; then
	    echo "done"
        else
            echo "failed"
            exit $?
        fi
}

case "$1" in
  start)
	startdaemon
	;;
  stop)
  	stopdaemon
	;;
  restart)
	stopdaemon
	startdaemon
	;;
  reload)
	pid=$(cat $PIDFILE)
	if [ -z $pid ]; then
		echo "M1M3 Thermal System CSC isn't running."
	else
		echo -n "Triggering M1M3 Thermal System configuration reload - pid ${pid}"
		/bin/kill -SIGUSR1 ${pid}
		echo "..$? done. Check M1M3 log for confirmation!"
	fi
	;;
  status)
	status $DAEMON
	exit $?
	;;
  *)
	echo "Usage: ts-M1M3thermal { start | stop | status | restart }" >&2
	exit 1
	;;
esac

exit 0
